  documentation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Generate automated documentation
      run: |
        echo "📚 Generating documentation..."
        mkdir -p docs
        current_time=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        echo "# 🚀 Automated Build Report" > docs/build_report.md
        echo "" >> docs/build_report.md
        echo "## 📊 Build Information" >> docs/build_report.md
        echo "- **Build Date:** $current_time" >> docs/build_report.md
        echo "- **Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})" >> docs/build_report.md
        echo "- **Branch:** ${{ github.ref }}" >> docs/build_regit port.md
        echo "- **Workflow Run:** [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> docs/build_report.md
        echo "" >> docs/build_report.md
        echo "## ✅ Test Status" >> docs/build_report.md
        echo "All tests passed successfully! 🎉" >> docs/build_report.md
        echo "" >> docs/build_report.md
        echo "## 📈 Code Metrics" >> docs/build_report.md
        echo "- **Python Files:** $(find . -name '*.py' -not -path './.git/*' | wc -l)" >> docs/build_report.md
        echo "- **Test Files:** $(find tests -name '*.py' | wc -l)" >> docs/build_report.md
        echo "- **Total Lines of Code:** $(find . -name '*.py' -not -path './.git/*' | xargs wc -l | tail -1 | awk '{print $1}')" >> docs/build_report.md
        echo "" >> docs/build_report.md
        echo "---" >> docs/build_report.md
        echo "*Automatically generated by GitHub Actions*" >> docs/build_report.md
        
        echo "✅ Documentation generated successfully"
        echo "📄 Content of build_report.md:"
        cat docs/build_report.md
        
    - name: Commit and push documentation
      run: |
        echo "🚀 Committing documentation updates..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Добавляем все изменения в документации
        git add docs/
        
        # Проверяем есть ли изменения для коммита
        if git diff --staged --quiet; then
          echo "📝 No changes to commit in documentation"
        else
          git commit -m "📚 docs: auto-update build report for ${{ github.sha }}"
          echo "✅ Changes committed successfully"
          git push
          echo "🚀 Documentation pushed to repository"
        fi